## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 's2qt_odmr' 

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_template' #to modify
description = 'Plugin to use a Rohde & Schwarz MW source and a NI DAQmx card to perform ODMR measurements'

author = 'Aurore Finco'
author-email = 'aurore.finco@umontpellier.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq_plugins_rohdeschwarz', 'pymodaq_plugins_daqmx', 'pymodaq>=4.0.0']
